#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/s5e9925-common

PRODUCT_COPY_FILES += \
    vendor/samsung/s5e9925-common/proprietary/product/etc/permissions/privapp-permissions-google-product.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/privapp-permissions-google-product.xml \
    vendor/samsung/s5e9925-common/proprietary/system_ext/etc/permissions/com.android.hotwordenrollment.common.util.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.android.hotwordenrollment.common.util.xml \
    vendor/samsung/s5e9925-common/proprietary/vendor/etc/Khronos/OpenCL/samsung.icd:$(TARGET_COPY_OUT_VENDOR)/etc/Khronos/OpenCL/samsung.icd \
    vendor/samsung/s5e9925-common/proprietary/vendor/etc/LVACFS_Calibration.dat:$(TARGET_COPY_OUT_VENDOR)/etc/LVACFS_Calibration.dat \
    vendor/samsung/s5e9925-common/proprietary/vendor/etc/LVACFS_Configuration.txt:$(TARGET_COPY_OUT_VENDOR)/etc/LVACFS_Configuration.txt \
    vendor/samsung/s5e9925-common/proprietary/vendor/etc/LVACFS_ControlParams.txt:$(TARGET_COPY_OUT_VENDOR)/etc/LVACFS_ControlParams.txt \
    vendor/samsung/s5e9925-common/proprietary/vendor/etc/SoundBoosterParam.txt:$(TARGET_COPY_OUT_VENDOR)/etc/SoundBoosterParam.txt \
    vendor/samsung/s5e9925-common/proprietary/vendor/etc/audio_board_info.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_board_info.xml \
    vendor/samsung/s5e9925-common/proprietary/vendor/etc/dolby/dax-default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dolby/dax-default.xml \
    vendor/samsung/s5e9925-common/proprietary/vendor/etc/dqe/DQE_coef_data.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dqe/DQE_coef_data.xml \
    vendor/samsung/s5e9925-common/proprietary/vendor/etc/dqe/calib_data_atc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dqe/calib_data_atc.xml \
    vendor/samsung/s5e9925-common/proprietary/vendor/etc/dqe/calib_data_bypass.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dqe/calib_data_bypass.xml \
    vendor/samsung/s5e9925-common/proprietary/vendor/etc/dqe/calib_data_colortemp.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dqe/calib_data_colortemp.xml \
    vendor/samsung/s5e9925-common/proprietary/vendor/etc/dqe/calib_data_eyetemp.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dqe/calib_data_eyetemp.xml \
    vendor/samsung/s5e9925-common/proprietary/vendor/etc/dqe/calib_data_rgbgain.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dqe/calib_data_rgbgain.xml \
    vendor/samsung/s5e9925-common/proprietary/vendor/etc/dqe/calib_data_skincolor.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dqe/calib_data_skincolor.xml \
    vendor/samsung/s5e9925-common/proprietary/vendor/etc/dqe/calib_data_whitepoint.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dqe/calib_data_whitepoint.xml \
    vendor/samsung/s5e9925-common/proprietary/vendor/etc/gnss/ca.pem:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/ca.pem \
    vendor/samsung/s5e9925-common/proprietary/vendor/etc/gnss/gps.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/gps.cfg \
    vendor/samsung/s5e9925-common/proprietary/vendor/etc/hdr_samsung_mx.key:$(TARGET_COPY_OUT_VENDOR)/etc/hdr_samsung_mx.key \
    vendor/samsung/s5e9925-common/proprietary/vendor/etc/init/android.hardware.drm@1.4-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.4-service.widevine.rc \
    vendor/samsung/s5e9925-common/proprietary/vendor/etc/init/android.hardware.security.keymint-service.samsung.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.security.keymint-service.samsung.rc \
    vendor/samsung/s5e9925-common/proprietary/vendor/etc/init/hermesd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hermesd.rc \
    vendor/samsung/s5e9925-common/proprietary/vendor/etc/init/init.baseband.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.baseband.rc \
    vendor/samsung/s5e9925-common/proprietary/vendor/etc/init/init.gps.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.gps.rc \
    vendor/samsung/s5e9925-common/proprietary/vendor/etc/init/init.vendor.rilcommon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vendor.rilcommon.rc \
    vendor/samsung/s5e9925-common/proprietary/vendor/etc/init/teegris_v4.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/teegris_v4.rc \
    vendor/samsung/s5e9925-common/proprietary/vendor/etc/init/vendor.samsung.hardware.gnss@2.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.gnss@2.1-service.rc \
    vendor/samsung/s5e9925-common/proprietary/vendor/etc/init/vendor.samsung.rilchip.slsi.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.rilchip.slsi.rc \
    vendor/samsung/s5e9925-common/proprietary/vendor/etc/init/vendor.samsung.rild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.rild.rc \
    vendor/samsung/s5e9925-common/proprietary/vendor/etc/mtu-conf.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mtu-conf.xml \
    vendor/samsung/s5e9925-common/proprietary/vendor/etc/secnvm/k250a_47000301_0.img:$(TARGET_COPY_OUT_VENDOR)/etc/secnvm/k250a_47000301_0.img \
    vendor/samsung/s5e9925-common/proprietary/vendor/etc/secnvm/k250a_47000305_c.img:$(TARGET_COPY_OUT_VENDOR)/etc/secnvm/k250a_47000305_c.img \
    vendor/samsung/s5e9925-common/proprietary/vendor/etc/secnvm/k250a_47000306_1.img:$(TARGET_COPY_OUT_VENDOR)/etc/secnvm/k250a_47000306_1.img \
    vendor/samsung/s5e9925-common/proprietary/vendor/etc/sound_trigger_info.xml:$(TARGET_COPY_OUT_VENDOR)/etc/sound_trigger_info.xml \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/APBargeIn_AUDIO_SLSI.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/APBargeIn_AUDIO_SLSI.bin \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/APDV_AUDIO_SLSI.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/APDV_AUDIO_SLSI.bin \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/APSV_AUDIO_SLSI.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/APSV_AUDIO_SLSI.bin \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/AP_AUDIO_SLSI.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/AP_AUDIO_SLSI.bin \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/OD_V3.4.3_08_31_QVGA_PAMIR_ENN_BGRA.nnc:$(TARGET_COPY_OUT_VENDOR)/firmware/OD_V3.4.3_08_31_QVGA_PAMIR_ENN_BGRA.nnc \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/OD_V3.5.2_08_31_VGA_PAMIR_ENN_BGRA.nnc:$(TARGET_COPY_OUT_VENDOR)/firmware/OD_V3.5.2_08_31_VGA_PAMIR_ENN_BGRA.nnc \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/SoundBoosterParam.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/SoundBoosterParam.bin \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/a2dpcom.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/a2dpcom.bin \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/abox_tplg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/abox_tplg.bin \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/abox_tplg.conf:$(TARGET_COPY_OUT_VENDOR)/firmware/abox_tplg.conf \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/avsyncmix.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/avsyncmix.bin \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/bidirmic.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/bidirmic.bin \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/calliope_dram.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/calliope_dram.bin \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/cs40l26-a2h.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-a2h.bin \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/cs40l26-svc.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-svc.bin \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/cs40l26-svc1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-svc1.bin \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/cs40l26-svc2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-svc2.bin \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/cs40l26-svc3.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-svc3.bin \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/cs40l26.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26.wmfw \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/dax_param.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dax_param.bin \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/default_configuration.flm.cfg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/default_configuration.flm.cfg.bin \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/dolby.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dolby.bin \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/dsp_gkt.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/dsp_gkt.xml \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/dsp_ivp_dm.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dsp_ivp_dm.bin \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/dsp_ivp_pm.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dsp_ivp_pm.bin \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/dsp_reloc_rules.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dsp_reloc_rules.bin \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/icc_profile.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/icc_profile.bin \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/leaudio_dec.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/leaudio_dec.bin \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/leaudio_enc.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/leaudio_enc.bin \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/libann.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/libann.elf \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/libgaussian3x3.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/libgaussian3x3.elf \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/libivp.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/libivp.elf \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/liblog.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/liblog.elf \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/libme_rta_pamir.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/libme_rta_pamir.elf \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/libnn.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/libnn.elf \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/libnn_af16wf16.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/libnn_af16wf16.elf \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/libnn_sdma.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/libnn_sdma.elf \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/listenbackeffect.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/listenbackeffect.bin \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/mfc/mfc_fw_flash.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mfc/mfc_fw_flash.bin \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/mfc/mfc_fw_flash_s2miw04.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mfc/mfc_fw_flash_s2miw04.bin \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/rxse.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/rxse.bin \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/sb_ll.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sb_ll.bin \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/sb_music.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sb_music.bin \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/sb_others.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sb_others.bin \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/secnvm/k250a_fw_image.manifest:$(TARGET_COPY_OUT_VENDOR)/firmware/secnvm/k250a_fw_image.manifest \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/sectiongraph_tplg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sectiongraph_tplg.bin \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/sectiongraph_tplg.conf:$(TARGET_COPY_OUT_VENDOR)/firmware/sectiongraph_tplg.conf \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/secure_configuration.flm.cfg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/secure_configuration.flm.cfg.bin \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/txse1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/txse1.bin \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/txse2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/txse2.bin \
    vendor/samsung/s5e9925-common/proprietary/vendor/firmware/volumemonitor.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/volumemonitor.bin

PRODUCT_PACKAGES += \
    libEGL_samsung \
    libGLESv1_CM_samsung \
    libGLESv2_samsung \
    sound_trigger.primary.s5e9925 \
    vulkan.samsung \
    libOpenCL \
    libSGPUOpenCL \
    libfloatingfeature \
    libsecnativefeature \
    libsecril-client \
    sensors.flicker \
    vendor.samsung.libcolor.hardware \
    vendor.samsung.libcolor.hdr10plus \
    audio.primary.s5e9925 \
    vendor.samsung_slsi.hardware.ExynosA2DPOffload@3.0-impl \
    libSamsungPostProcessConvertor \
    lib_SamsungRec_08020 \
    lib_SoundAlive_3DPosition_ver202 \
    lib_SoundAlive_AlbumArt_ver105 \
    lib_SoundAlive_SRC384_ver320 \
    lib_SoundAlive_play_plus_ver800 \
    lib_SoundBooster_ver1100 \
    lib_lvacfs \
    lib_soundaliveresampler \
    libaboxpcmdump \
    libalsautils_sec \
    libaudio-ril \
    libaudioparamupdate \
    libaudioproxy2 \
    libaudioroute_samsung \
    libdatamod \
    liblastaboxmsg \
    libprofileparamstorage \
    librecordalive \
    libsecaudiocoreutils \
    libsecaudioinfo \
    libsehbluetooth_audio_session \
    libspatializerparamstorage \
    libspeakercalibration \
    libtinyalsa_samsung \
    libvibrator_vendor \
    libaudioeffectoffload \
    libhapticgenerator \
    libmyspace \
    vendor.samsung.hardware.bluetooth.a2dp@1.0 \
    vendor.samsung.hardware.bluetooth.audio@2.0 \
    vendor.samsung.hardware.bluetooth.audio@2.1 \
    vendor.samsung_slsi.hardware.ExynosA2DPOffload@3.0 \
    android.hardware.gnss@2.1-impl \
    gatekeeper.s5e9925 \
    vendor.samsung.hardware.gnss@2.1-impl \
    libIMUSensor \
    libImageFormatConverter \
    libMERTA \
    libVendorSemDataProps \
    libVendorSemTelephonyProps \
    lib_android_keymaster_skeymint_utils \
    libbauthserver \
    libbauthtzcommon \
    libcrypto-tm \
    libegis_fp_normal_sensor_test \
    libeis_core \
    libengmode_client \
    libenn_common_utils \
    libenn_engine_lib \
    libenn_model \
    libenn_profiler \
    libenn_public_api_cpp_lib \
    libenn_user_driver_cpu \
    libenn_user_driver_gpu_lib \
    libenn_user_driver_unified \
    libenn_user_lib \
    libepic_helper \
    libexynoscamera_cnr_plugin \
    libexynoscamera_fakefusion \
    libexynoscamera_fakefusion_plugin \
    libexynoscamera_plugin \
    libexynoscamera_plugin_utils \
    libgf_in_system_lib \
    libhermes_bdbridge \
    libhermes_cred \
    libhwjsqz \
    libhwvault \
    libkeymaster_portable.samsung \
    libmpbase \
    libqfp_sensortest \
    librechdr10plus.plugin \
    librechdr10plus \
    libril_sem \
    libsec-ril \
    libsemnativecarrierfeature \
    libsemseg \
    libsensorlistener \
    libshctrl \
    libskeymint \
    libskeymint10device \
    libskeymint_cli \
    libsn220u_fw \
    libswcnr \
    libsynaFpSensorTestNwd \
    libteecl \
    libtriplecam_image_optical_zoom \
    libtriplecam_video_optical_zoom \
    libtriplecapture_interface \
    libtriplepreview_interface \
    libuniapi \
    libuniplugin \
    libuuid_vendor \
    libvdis_core \
    libvdis_interface \
    libvkmanager_vendor \
    libvpl \
    libwrappergps \
    libwvhidl \
    vendor.samsung.hardware.biometrics.fingerprint@3.0 \
    vendor.samsung.hardware.gnss@2.0 \
    vendor.samsung.hardware.gnss@2.1 \
    vendor.samsung.hardware.keymint-V1-ndk_platform \
    vendor.samsung.hardware.radio-V1-ndk \
    vendor.samsung.hardware.radio.bridge-V1-ndk \
    vendor.samsung.hardware.radio.channel-V1-ndk \
    vendor.samsung.hardware.radio.data-V1-ndk \
    vendor.samsung.hardware.radio.messaging-V1-ndk \
    vendor.samsung.hardware.radio.sim-V1-ndk \
    vendor.samsung.hardware.security.drk-V1-ndk_platform \
    vendor.samsung.hardware.security.drk@2.0 \
    vendor.samsung.hardware.security.hermes-V1-ndk_platform \
    vendor.samsung.hardware.thermal@1.0 \
    vendor.samsung_slsi.hardware.enn@1.0 \
    HotwordEnrollmentOKGoogleEx4CORTEXM55 \
    HotwordEnrollmentXGoogleEx4CORTEXM55 \
    com.android.hotwordenrollment.common.util \
    manifest_android.hardware.drm@1.4-service.widevine.xml \
    vendor.samsung.hardware.radio_manifest_2_34.xml \
    vendor.samsung.hardware.sehradio_manifest_2_34.xml \
    hermesd \
    android.hardware.drm@1.4-service.widevine \
    android.hardware.security.keymint-service.samsung \
    gps \
    rild \
    vendor.samsung.hardware.gnss@2.1-service \
    tzdaemon \
    tzts_daemon

PRODUCT_PACKAGES += \
    vendor_Khronos_OpenCL_vendors_samsung_icd
